
model:
  backbone: 'vgg'
  cfr: False #True
  cfr_layer: 21
  amp: False
  cuda: True
  multi_fc: False
  k_count: 4

attack:
  adv_type: 'mtd'
  atk_iters: 20
  step_size: 8

data:
  dataset: 'VOC'
  dataset_root: '../datas/VOCdevkit/'
  data_use: 'clean[2007]+clean[2012]'
  num_workers: 0 #8

train:
  basenet: 'weights/ssd300_mAP_77.43_v2.pth'
  batch_size: 4 #32
  resume: 'weights/ssd300_VOC_adv-mtd_dconv4_step8_clean_rec21_final_40000.pth' #null
  start_iter: 40000
  multi_gpu: False
  lr: 0.0001
  max_iter: 80000
  momentum: 0.9
  weight_decay: 0.0005
  gamma: 0.1
  focal: False
  adc: 0
  save_folder: 'weights/'
  log_folder: 'logs/'

test:
  trained_model: ''
  save_folder: 'eval/'
  confidence_threshold: 0.01
  top_k: 5
  robust: True
  con_weights: [1.,1.]
  save_tp_fp: None
  log_folder: 'logs/'